/*
 * This source file was generated by the Gradle 'init' task
 */
package docentilmp;

public class main {


    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
